#version: '3.4'

x-qwc-service-variables: &qwc-service-variables
  JWT_SECRET_KEY: $JWT_SECRET_KEY
  JWT_COOKIE_CSRF_PROTECT: "True"
  JWT_COOKIE_SAMESITE: "Strict"
  # Uncomment if the application is exclusively run over HTTPS to ensure cookies are only sent with HTTPS requests
  # JWT_COOKIE_SECURE: 'True'
  # Set these to override the UID/GID which runs uwsgi. Useful to ensure uwsgi runs under the same user/group
  # which owns the shared volumes on host, avoiding the need to change the ownership/permissions of those files/folders.
  # SERVICE_UID: 1000
  # SERVICE_GID: 1000
  # Uncomment this for multi-tenant support, see also api-gateway/nginx-example-multitenant.conf
  # TENANT_HEADER: Tenant

services:
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
    # Port: MySQL (3306), PostgreSQL (5432)
    command: /cloud_sql_proxy -instances=PROJECT_ID:DATABASE_ZONE:DATABASE_INSTANCE=tcp:0.0.0.0:DATABASE_PORT -credential_file=/config/service-account-key.json
    volumes:
      # Mount service account key file
      # Create one at: https://console.cloud.google.com/iam-admin/serviceaccounts
      # Download the JSON key and save it as service-account-key.json in this directory
      - ./cloud-sql-proxy-service-account-key.json:/config/service-account-key.json:ro
    ports:
      - 5432:5432

  # Service client PostgreSQL pour se connecter à Cloud SQL via le proxy
  postgres-client:
    image: postgres:16-alpine
    depends_on:
      - cloud-sql-proxy
    env_file: "postgres-client.env"
    volumes:
      - ./pg_service.gcp.conf:/etc/pg_service.conf:ro
      - ./volumes/demo-data/sql:/docker-entrypoint-initdb.d/sql
      #- ./volumes/demo-data/check-database.sh:/docker-entrypoint-initdb.d/1_check-database.sh
      - ./volumes/demo-data/setup-roles-and-db.sh:/docker-entrypoint-initdb.d/2_setup-roles-and-db.sh
      - ./volumes/demo-data/setup-passwords.sh:/docker-entrypoint-initdb.d/3_setup-passwords.sh
      - ./volumes/demo-data/setup-demo-data.sh:/docker-entrypoint-initdb.d/4_setup-demo-data.sh
    networks:
      - default

  # Service de migration de la base de données QWC Config DB
  qwc-config-db-migrate:
    image: sourcepole/qwc-base-db-migrate:latest
    depends_on:
      - cloud-sql-proxy
      - postgres-client
    env_file: "postgres-client.env"
    environment:
      PGSERVICEFILE: "/tmp/pg_service.conf"
      PGSERVICE: "qwc_configdb"
      ALEMBIC_VERSION: "head"
      QWC_CONFIG_SCHEMA: "qwc_config"
    volumes:
      - ./pg_service.gcp.conf:/tmp/pg_service.conf:ro
      - ./volumes/demo-data/setup-demo-data-permissions.sh:/docker-entrypoint-initdb.d/1_setup-demo-data-permissions.sh
    networks:
      - default

