[vef_atlas]
host=cloud-sql-proxy
port=5432
dbname=eleonore
user=vef_admin
sslmode=disable

[qwc_configdb]
host=cloud-sql-proxy
port=5432
dbname=qwc_services
user=qwc_admin
password=qwc_admin
sslmode=disable

[qwc_geodb]
host=cloud-sql-proxy
port=5432
dbname=qwc_services
user=qwc_service_write
password=qwc_service_write
sslmode=disable
