apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: atlas-qwc-volume-read-only-many
  name: atlas-qwc-volume-read-only-many
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi

