apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: atlas-qwc-volume-read-write-once
  name: atlas-qwc-volume-read-write-once
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

