apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: qwc-map-viewer
  name: qwc-map-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qwc-map-viewer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: qwc-map-viewer
    spec:
      containers:
        - env:
            - name: JWT_COOKIE_CSRF_PROTECT
              value: "True"
            - name: JWT_COOKIE_SAMESITE
              value: Strict
            - name: JWT_SECRET_KEY
              value: d9532b1f681d5f40afa49f7cfbceaf5f4bf3eb879d12cb12889c30648f714ac148a1c73967edf001b83f6b0c9f705cd8
            - name: SERVICE_MOUNTPOINT
              value: /
          image: sourcepole/qwc-map-viewer:latest
          name: qwc-map-viewer
          volumeMounts:
            - mountPath: /srv/pg_service.conf
              name: atlas-qwc-db-config
              readOnly: true
              subPath: pg_service.conf
            - mountPath: /srv/qwc_service/config
              name: qwc-map-viewer-cm1
              readOnly: true
            - mountPath: /qwc2/assets
              name: qwc-map-viewer-cm2
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: pg_service.conf
                path: pg_service.conf
            name: atlas-qwc-db-config
          name: atlas-qwc-db-config
        - configMap:
            name: qwc-map-viewer-cm1
          name: qwc-map-viewer-cm1
        - configMap:
            name: qwc-map-viewer-cm2
          name: qwc-map-viewer-cm2
