apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: qwc-qgis-server
  name: qwc-qgis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qwc-qgis-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: qwc-qgis-server
    spec:
      containers:
        - env:
            - name: FCGID_EXTRA_ENV
              value: PRINT_LAYOUT_DIR
            - name: PRINT_LAYOUT_DIR
              value: /layouts
            - name: QGIS_SERVER_CACHE_DIRECTORY
              value: /tmp/qgis-cache
            - name: QGIS_SERVER_CACHE_SIZE
              value: "100"
            - name: QGIS_SERVER_PARALLEL_RENDERING
              value: "1"
          image: sourcepole/qwc-qgis-server:3.40
          name: qwc-qgis-server
          volumeMounts:
            - mountPath: /data
              name: atlas-qwc-qgis-ressources-config
              readOnly: true
            - mountPath: /etc/postgresql-common/pg_service.conf
              name: atlas-qwc-db-config
              readOnly: true
              subPath: pg_service.conf
            - mountPath: /usr/share/qgis/python/plugins/print_templates
              name: atlas-qwc-volume-read-only-many
              readOnly: true
            - mountPath: /usr/share/qgis/python/plugins/split_categorized
              name: atlas-qwc-volume-read-only-many
              readOnly: true
            - mountPath: /usr/share/qgis/python/plugins/filter_geom
              name: atlas-qwc-volume-read-only-many
              readOnly: true
            - mountPath: /usr/share/qgis/python/plugins/clear_capabilities
              name: atlas-qwc-volume-read-only-many
              readOnly: true
            - mountPath: /layouts
              name: atlas-qwc-print-layouts-config
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: atlas-qwc-qgis-ressources-config
          name: atlas-qwc-qgis-ressources-config
        - configMap:
            items:
              - key: pg_service.conf
                path: pg_service.conf
            name: atlas-qwc-db-config
          name: atlas-qwc-db-config
        - name: atlas-qwc-volume-read-only-many
          persistentVolumeClaim:
            claimName: atlas-qwc-volume-read-only-many
            readOnly: true
        - name: atlas-qwc-volume-read-only-many
          persistentVolumeClaim:
            claimName: atlas-qwc-volume-read-only-many
            readOnly: true
        - name: atlas-qwc-volume-read-only-many
          persistentVolumeClaim:
            claimName: atlas-qwc-volume-read-only-many
            readOnly: true
        - name: atlas-qwc-volume-read-only-many
          persistentVolumeClaim:
            claimName: atlas-qwc-volume-read-only-many
            readOnly: true
        - configMap:
            name: atlas-qwc-print-layouts-config
          name: atlas-qwc-print-layouts-config

